### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Dado1513** [Mobile-IoT-Security-Lab/HideDroid#3]
- [ ] Remove code comments on app code
- [ ] Suppot for Android version > 11 [test-android-11-support](https://github.com/Mobile-IoT-Security-Lab/HideDroid/tree/test-android-11-support)
- [ ]  Upload the video showing how the app works
